on:
  schedule:
    - cron:  '30 5,17 * * *'
  workflow_dispatch:

jobs:
  check-for-updates:
    strategy:
      matrix:
        repo:
          - git@salsa.debian.org:ubuntu-desktop-helper/epiphany-browser.git
          - git@salsa.debian.org:ubuntu-desktop-helper/gnome-software.git
          - git@salsa.debian.org:ubuntu-desktop-helper/gedit.git
          - git@salsa.debian.org:ubuntu-desktop-helper/gedit-plugins.git
          - git@salsa.debian.org:ubuntu-desktop-helper/glib.git
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y devscripts
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PUB_KEY }}" > ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 400 ~/.ssh/id_rsa
      - name: Clone repo
        run: |
          git clone ${{ matrix.repo }} project
      - name: Check for Update
        id: check-update
        continue-on-error: true
        run: |
          cd project
          uscan && echo "release=available" >> $GITHUB_OUTPUT
      - name: Create job
        if: steps.check-update.outputs.release == 'available'
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/ubuntu/deb-ci/actions/workflows/59636522/dispatches \
            -d '{"ref":"main","inputs":{"repo":"${{ matrix.repo }}"}}'
